### ISSUE TITLE
Fix: cannot have multiple apps using the library at the same time on the same device

### ISSUE THREAD

**Issue by marcanpilami** [enioka/enioka_scan#39]
It seems our services are public, which is weird. Probably simply a namespace issue (all our apps have the same vendor name or such?)

**Comment by DaSpood** [comment]
At the moment there is no clear explanation why the `exported=false` attribute in service declarations is not enough to stop them from being used by other apps using the same library.

I suspect discovering services with `queryIntentServices()` simply lists all matching services regardless of whether or not they are exported (thus whether or not they can be created/used by implicit intent). Services are then bound by explicit intent, which bypasses the `exported` attribute that seems to only affect use by implicit intents. And since sdk services have the same name and package name for all apps they may conflict there. For that reason, skipping services with a different UID during discovery does not affect the app's behavior or fix any observed issue, and I have not found another way to avoid using unwanted services.

I have also not observed any crash or severe bug rendering the application unusable when two of them are on at the same time. The scanner sometimes does not work properly immediately when switching to the app from another scanner app, but simply exiting and restarting the view seems to make it work again.

Issue will likely be fixed while addressing #44 and #45 (#25) and might require moving away from provider services.
